### ISSUE TITLE
Third Party Mod Axe(s)

### ISSUE THREAD

**Issue by Tabascopunk** [UpcraftLP/Hardcore-Survival-1.10#6]
When using a mod that offers an axe, or form of an axe (i.e., a paxel*), it seems to not recognize it as such and just destroys the wood.

A good example is the ReinforcedTools mod's paxels. Not sure on whose end of this the issue would lie, but I really enjoy your mod and would love to be able to include it.

**Comment by UpcraftLP** [comment]
In which Minecraft version did you find this bug? Also which version of ReinforcedTools did you use?
EDIT: nvm, I tested against the latest version.

**Comment by UpcraftLP** [comment]
The issue is caused by the ReinforcedTools paxel not registering the proper tool classes. 
(I check if the Item used to harvest is either a vanilla ItemAxe or has the "axe" tool class [here](https://github.com/UpcraftLP/Hardcore-Survival/blob/Hardcore-Survival-1.11/src/main/java/mod/upcraftlp/hardcoresurvival/events/WoodEvents.java#L30)).
I'll write a comment on their CurseForge page.

**Comment by UpcraftLP** [comment]
C6H2Cl2 stated that the issue is fixed in his next release on 12/22. ([original post](https://minecraft.curseforge.com/projects/reinforcedtools#c22))

**Comment by Tabascopunk** [comment]
That's great!
